In [1]:
from src.utils import get_constants, update_constants, delete_constants, create_constants

In [3]:
get_constants('project_start_date')

FileNotFoundError: [Errno 2] No such file or directory: './constants.json'

In [10]:
import torch

matrix = [[0, 4, 9], [3.5, 0, 4.5], [99.9, 499.75, 0]]

tensor = torch.tensor(matrix)

print(tensor)


tensor([[  0.0000,   4.0000,   9.0000],
        [  3.5000,   0.0000,   4.5000],
        [ 99.9000, 499.7500,   0.0000]])


In [14]:
update_constants({'device': 'cpu'})

0

In [4]:
get_constants(['project_start_date', 'Temp'])

{'project_start_date': 'Not 17 PAril 2023', 'Temp': 'This is a temp value'}

In [15]:
delete_constants('Temp')

KeyError: 'Temp'

In [24]:
true_labels = torch.tensor([[1.0, 0 , 0], [0, 1.0, 0], [0, 0, 1.0]])
pred_labels = torch.tensor([[1.0, 0 , 0], [0, 0, 1.0], [1.0, 0, 0.0]])
tensor

tensor([[  0.0000,   4.0000,   9.0000],
        [  3.5000,   0.0000,   4.5000],
        [ 99.9000, 499.7500,   0.0000]])

In [25]:
torch.matmul(true_labels, torch.matmul(tensor, pred_labels).T)

tensor([[  9.0000,   8.0000,  99.9000],
        [  0.0000,   0.0000,   0.0000],
        [  4.0000,   0.0000, 499.7500]])

In [28]:
import torch

# Create an empty list to store the results
results = []

# Loop through each row of true and pred
for i in range(len(true_labels)):
    # Extract the ith row of true and pred
    true_i = true_labels[i].unsqueeze(0)  # Add a dimension of size 1 to make it a row vector
    pred_i = pred_labels[i].unsqueeze(0)  # Add a dimension of size 1 to make it a row vector
    print(true_i, pred_i)
    # Compute the product in the specified order
    product = true_i.mm(tensor).mm(pred_i.t())  # .t() is used to transpose pred_i
    
    # Add the result to the list of results
    results.append(product)

# Concatenate the results along the first dimension to get the final output
output = torch.cat(results, dim=0)


tensor([[1., 0., 0.]]) tensor([[1., 0., 0.]])
tensor([[0., 1., 0.]]) tensor([[0., 0., 1.]])
tensor([[0., 0., 1.]]) tensor([[1., 0., 0.]])


In [29]:
output

tensor([[ 0.0000],
        [ 4.5000],
        [99.9000]])

In [31]:
sum(output).item()

104.4000015258789

In [32]:
results

[tensor([[0.]]), tensor([[4.5000]]), tensor([[99.9000]])]

In [33]:
results.sum()

AttributeError: 'list' object has no attribute 'sum'

In [2]:
train_transform = {
"TRAIN_TRANSFORM_RESIZE": 224,
"TRAIN_HORI_FLIP": True,
"COLORJITTER_BRIGHTNESS": 0.4,
"COLORJITTER_CONTRAST": 0.4,
"COLORJITTER_SATURATION": 0.4,
"COLORJITTER_HUE": 0.1,
"RANDOMROTATION_DEGREES": 20,
"TRAIN_TRANSFORM_MEAN": [0.485, 0.456, 0.406],
"TRAIN_TRANSFORM_STD": [0.229, 0.224, 0.225]
}

val_transform = {
    "VAL_TRANSFORM_RESIZE": 256,
    "VAL_TRANSFORM_CROP": 224,
    "VAL_TRANSFORM_MEAN": [0.485, 0.456, 0.406],
    "VAL_TRANSFORM_STD": [0.229, 0.224, 0.225]
}

In [3]:
create_constants(train_transform)
create_constants(val_transform)

0